/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import edu.princeton.cs.algs4.DirectedEdge;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;

import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import edu.princeton.cs.algs4.Edge;
import edu.princeton.cs.algs4.EdgeWeightedDigraph;
import edu.princeton.cs.algs4.EdgeWeightedGraph;
import edu.princeton.cs.algs4.In;
import edu.princeton.cs.algs4.Out;
import edu.princeton.cs.algs4.RedBlackBST;
import edu.princeton.cs.algs4.StdOut;

/**
 *
 * @author Jeffrey L, Andy Tran
 */
public class StockApp extends javax.swing.JFrame
{
   private final int ID_COL_INDEX = 0;
   private final int CODE_COL_INDEX = 1;
   private final int NAME_COL_INDEX = 2;
   private final int PRICE_COL_INDEX = 3;
   private final int QTY_COL_INDEX = 4;
   private final int DEPT_COL_INDEX = 5;
   private final int DATE_COL_INDEX = 6;
   private final int SHIP_COL_INDEX = 7; 
    
    // fields   
    private DefaultTableModel model;
    private DefaultTableModel orderModel;       
    private RedBlackBST<Integer, Items> st;
    private RedBlackBST<String, ArrayList<ShipItems>> orderST;
    private EdgeWeightedSymbolDigraph sg;
    
    private String[] orderHead = {"ID","Name","Code","Price","Qty","Department","Date Created","Ship to"};
    private String[] tableHead={"ID","Name","Code","Price","Qty","Department","Date Created"};
    private String[] cities;

    public StockApp()
    {
        // Create and Show UI
        initComponents();
        this.setLocationRelativeTo(null);
        
       st = new RedBlackBST<>();
       orderST = new RedBlackBST<>();
        // create table
        Date date = Calendar.getInstance().getTime();
        In in = new In("src/Resources/items.csv");
        in.readLine();
        while (in.hasNextLine()) {
            String[] newRow = in.readLine().split(",");

            String name = newRow[NAME_COL_INDEX];
            String code= newRow[CODE_COL_INDEX];
            double price = Double.parseDouble(newRow[PRICE_COL_INDEX]);
            int qty = Integer.parseInt(newRow[QTY_COL_INDEX]);
            String department = newRow[DEPT_COL_INDEX+1];

            Items newItem = new Items(code, name, price, qty, date, department);
            st.put(newItem.getId(), newItem);
        }
	printST();

        // Create Table in Modify Tab
        String[][] tableData = createTable();
        model = new DefaultTableModel(tableData, tableHead);
        table.setModel(model);
        
        // Create Table in Order Tab
        String[][] orderData = {};
        orderModel = new DefaultTableModel(orderData, orderHead);
        orderTable.setModel(orderModel);
        
        // Read file and grab the grap
        String filename  = "src/Resources/city.csv";
        String delimiter = ",";
        sg = new EdgeWeightedSymbolDigraph(filename, delimiter);
        
        // Get the all the cities from the graph
        cities = getCities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenuItem1 = new javax.swing.JMenuItem();
        tabbedPane = new javax.swing.JTabbedPane();
        panel1 = new javax.swing.JPanel();
        addItem = new javax.swing.JButton();
        deleteItem = new javax.swing.JButton();
        editItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pieChartBtn1 = new javax.swing.JButton();
        barChartBtn1 = new javax.swing.JButton();
        exportBtn1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        panel2 = new javax.swing.JPanel();
        addOrder = new javax.swing.JButton();
        deleteOrder = new javax.swing.JButton();
        editOrder = new javax.swing.JButton();
        shipment = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock Manage System");

        addItem.setText("Add Item");
        addItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addItemActionPerformed(evt);
            }
        });

        deleteItem.setText("Delete Item");
        deleteItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteItemActionPerformed(evt);
            }
        });

        editItem.setText("Edit Item");
        editItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                editItemActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "ID", "Name", "Code", "Price", "Qty", "Department", "Date Created"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table.setRowHeight(25);
        table.setSelectionBackground(new java.awt.Color(0, 153, 204));
        table.setShowVerticalLines(false);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        table.getAccessibleContext().setAccessibleName("orderTable");

        pieChartBtn1.setBackground(new java.awt.Color(0, 153, 255));
        pieChartBtn1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pieChartBtn1.setText("Pie Chart");
        pieChartBtn1.setSelected(true);
        pieChartBtn1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pieChartBtn1ActionPerformed(evt);
            }
        });

        barChartBtn1.setBackground(new java.awt.Color(0, 153, 255));
        barChartBtn1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        barChartBtn1.setText("Bar Chart");
        barChartBtn1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                barChartBtn1ActionPerformed(evt);
            }
        });

        exportBtn1.setBackground(new java.awt.Color(0, 153, 255));
        exportBtn1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        exportBtn1.setText("Excel File");
        exportBtn1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exportBtn1ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label1.setText("Export");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pieChartBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(barChartBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pieChartBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barChartBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exportBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        addItem.getAccessibleContext().setAccessibleName("addItem");
        deleteItem.getAccessibleContext().setAccessibleName("deleteItem");
        editItem.getAccessibleContext().setAccessibleName("editItem");

        tabbedPane.addTab("Modify", panel1);
        panel1.getAccessibleContext().setAccessibleName("Modify");

        addOrder.setText("Add Order");
        addOrder.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addOrderActionPerformed(evt);
            }
        });

        deleteOrder.setText("Delete Order");
        deleteOrder.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteOrderActionPerformed(evt);
            }
        });

        editOrder.setText("Edit Order");
        editOrder.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                editOrderActionPerformed(evt);
            }
        });

        shipment.setText("Shipment");
        shipment.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                shipmentActionPerformed(evt);
            }
        });

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "ID", "Name", "Code", "Price", "Qty", "Department", "Date Created", "Ship to"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        orderTable.setFocusable(false);
        orderTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        orderTable.setRowHeight(25);
        orderTable.setSelectionBackground(new java.awt.Color(232, 57, 95));
        orderTable.setShowVerticalLines(false);
        orderTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(orderTable);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel2Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(addOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                            .addComponent(deleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shipment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(addOrder)
                .addGap(7, 7, 7)
                .addComponent(deleteOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editOrder)
                .addGap(32, 32, 32)
                .addComponent(shipment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        addOrder.getAccessibleContext().setAccessibleName("addOrder");
        deleteOrder.getAccessibleContext().setAccessibleName("deleteOrder");
        editOrder.getAccessibleContext().setAccessibleName("editOrder");
        shipment.getAccessibleContext().setAccessibleName("shipment");

        tabbedPane.addTab("Order", panel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        tabbedPane.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exportBtn1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exportBtn1ActionPerformed
    {//GEN-HEADEREND:event_exportBtn1ActionPerformed
     
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Export File");
        chooser.setFileFilter(new FileTypeFilter(".csv", "CSV File"));

        // Export the .csv file
        int result = chooser.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            try{
                File f = chooser.getSelectedFile();
                String fileName = f.getAbsolutePath();
                if(!fileName.contains(".csv")){
                    fileName += ".csv";
                }
                Out out = new Out(fileName);

               String head = "";
               for(int i = 0; i < tableHead.length; i++) {
                       if(i < tableHead.length - 1)
                               head = head + tableHead[i] + ",";
                       else {
                               head = head + tableHead[i] + "\n";
                       }
               }
               out.print(head);

               for(Integer k: st.keys()) {
                       String data = st.get(k).getString() + "\n";
                       out.print(data);
               }
               out.close();
               JOptionPane.showMessageDialog(null,
                                "Successfully Export file",
                                "Message",
                                JOptionPane.INFORMATION_MESSAGE);
            } catch(Exception e){
                               JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        
    }//GEN-LAST:event_exportBtn1ActionPerformed

    private void barChartBtn1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_barChartBtn1ActionPerformed
    {//GEN-HEADEREND:event_barChartBtn1ActionPerformed
	      BarChart barChart = new BarChart("Bar Chart", st);  
	      barChart.setSize(800, 400);  
	      barChart.setLocationRelativeTo(null);    
	      barChart.setVisible(true); 
    }//GEN-LAST:event_barChartBtn1ActionPerformed

    private void pieChartBtn1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pieChartBtn1ActionPerformed
    {//GEN-HEADEREND:event_pieChartBtn1ActionPerformed
	      PieChart  pieChart = new PieChart("Pie Chart", st);  
	      pieChart.setSize(600, 400);  
	      pieChart.setLocationRelativeTo(null);  			      
	      pieChart.setVisible(true); 
    }//GEN-LAST:event_pieChartBtn1ActionPerformed

    private void editItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_editItemActionPerformed
    {//GEN-HEADEREND:event_editItemActionPerformed
 
        if(table.getSelectedRow() != -1)
        {
            // Get data of chosen row
            int selectedRowIndex = table.getSelectedRow();

            JTextField[] fields = new JTextField[tableHead.length];
            JPanel panel = new JPanel(new GridLayout(0, 1));
            panel.setPreferredSize(null);

            for(int i = 1; i < tableHead.length - 1;i++)
            {
                panel.add(new JLabel(tableHead[i] + ":"));
                fields[i] = new JTextField();
                fields[i].setText(table.getModel().getValueAt(selectedRowIndex, i).toString());
                panel.add(fields[i]);
            }

            int result = JOptionPane.showConfirmDialog(null, panel, "Add Row", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION)
            {
                String id = table.getModel().getValueAt(selectedRowIndex, ID_COL_INDEX).toString();
                String date = table.getModel().getValueAt(selectedRowIndex, DATE_COL_INDEX).toString();
                for(Integer k: st.keys())
                {
                    if( Integer.parseInt(id) == k)
                    {
                        // Get the Text from User
                        Items editItem = st.get(k);
                        String[] editRow = new String[tableHead.length];
                        for (int i = 1; i < fields.length - 1; i++)
                        editRow[i] = fields[i].getText();
                        String name = editRow[NAME_COL_INDEX];
                        String code= editRow[CODE_COL_INDEX];
                        double price = Double.parseDouble(editRow[PRICE_COL_INDEX]);
                        int qty = Integer.parseInt(editRow[QTY_COL_INDEX]);
                        String department = editRow[DEPT_COL_INDEX];

                        // Update in Symbol Table
                        editItem.setName(name);
                        editItem.setCode(code);
                        editItem.setPrice(price);
                        editItem.setQuantity(qty);
                        editItem.setDepartment(department);
                        st.put(editItem.getId(), editItem);

                        // Update in GUI
                        table.getModel().setValueAt(id, selectedRowIndex, ID_COL_INDEX);
                        table.getModel().setValueAt(name, selectedRowIndex, NAME_COL_INDEX);
                        table.getModel().setValueAt(code, selectedRowIndex, CODE_COL_INDEX);
                        table.getModel().setValueAt(price, selectedRowIndex, PRICE_COL_INDEX);
                        table.getModel().setValueAt(qty, selectedRowIndex, QTY_COL_INDEX);
                        table.getModel().setValueAt(department, selectedRowIndex, DEPT_COL_INDEX);
                        table.getModel().setValueAt(editItem.getDateCreated(), selectedRowIndex, DATE_COL_INDEX);
                        break;
                    }
                }
            }
            printST();
        }
    }//GEN-LAST:event_editItemActionPerformed

    private void deleteItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteItemActionPerformed
    {//GEN-HEADEREND:event_deleteItemActionPerformed
        if(table.getSelectedRow() != -1)
        {
            // remove selected row from the model
            if (JOptionPane.showConfirmDialog(null, "Are you sure to delete this item?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                {
                    // yes option
                    int[] selectedRows = table.getSelectedRows();
                    for (int i = selectedRows.length - 1; i >= 0; i--)
                    {
                        int selectedRowIndex = selectedRows[i];
                        String id = table.getValueAt(selectedRowIndex, ID_COL_INDEX).toString();

                        for(Integer k: st.keys())
                        {
                            if( Integer.parseInt(id) == k)
                            {
                                st.delete(k);
                                break;
                            }
                        }
                        printST();
                        model.removeRow(selectedRowIndex);
                    }

                }
        }
    }//GEN-LAST:event_deleteItemActionPerformed

    private void addItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addItemActionPerformed
    {//GEN-HEADEREND:event_addItemActionPerformed
        JTextField[] fields = new JTextField[tableHead.length];

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.setPreferredSize(null);
        for (int i = 1; i < tableHead.length - 1; i++)
        {
            panel.add(new JLabel(tableHead[i] + ":"));
            fields[i] = new JTextField();
            panel.add(fields[i]);
        }

        int result = JOptionPane.showConfirmDialog(null, panel, "Add Row", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION)
        {
            String[] newRow = new String[tableHead.length];
            for (int i = 1; i < fields.length - 1; i++){
                newRow[i] = fields[i].getText();
            }

            String name = newRow[NAME_COL_INDEX];
            String code= newRow[CODE_COL_INDEX];            
            double price = Double.parseDouble(newRow[PRICE_COL_INDEX]);           
            int qty = Integer.parseInt(newRow[QTY_COL_INDEX]);
            String department = newRow[DEPT_COL_INDEX];
            
            // Get date using Calendar API
            Date date = Calendar.getInstance().getTime();           
            Items newItem = new Items(code, name, price, qty, date, department);   
            newRow[ID_COL_INDEX] = newItem.getId() + "";
            newRow[DATE_COL_INDEX] = newItem.getDateCreated();

            st.put(newItem.getId(), newItem);

            //Print after Adding
            printST();
            
            model.addRow(newRow);
        }

    }//GEN-LAST:event_addItemActionPerformed

    private void shipmentActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_shipmentActionPerformed
    {//GEN-HEADEREND:event_shipmentActionPerformed

        // Get all the cities that need to ship
        String[] shipCity = new String[orderST.size()];
        int i = 0;
        for(String k: orderST.keys()){
            ArrayList<ShipItems> a = orderST.get(k);
            if(!a.isEmpty()){
                shipCity[i] = k;
                i++;
            }
        }
        
        // Shortest Path go from the source to all the choosen cities      
        int source = sg.indexOf("Salt Lake City");
        ShortestPath sp = new ShortestPath(sg, shipCity, source);       
        String path = sp.getShortestPath();
        
        String[] pathing = Arrays.copyOf(shipCity, shipCity.length + 1);
        pathing[pathing.length-1] = sg.nameOf(source);
        
        try {
            Map.buildMap(pathing);
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        JOptionPane.showMessageDialog(null, path, "Shortest Path", JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_shipmentActionPerformed

    private void editOrderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_editOrderActionPerformed
    {//GEN-HEADEREND:event_editOrderActionPerformed
        if(orderTable.getSelectedRow() != -1)
        {
            // Get data of chosen row
            int selectedRowIndex = orderTable.getSelectedRow();
            
            // Pop up a Panel
            JPanel panel = new JPanel(new GridLayout(0, 3));
            JLabel label1 = new JLabel("Choosen Item");
            label1.setFont(new java.awt.Font("Tahoma", 1, 12));    
            JLabel label2 = new JLabel("Quantity");
            label2.setFont(new java.awt.Font("Tahoma", 1, 12));
            JLabel label3 = new JLabel("Ship To");
            label3.setFont(new java.awt.Font("Tahoma", 1, 12));
            
            // Get Choosen Item from Order Table
            String choosenItem = "";
            int id = Integer.parseInt(orderTable.getModel().getValueAt(selectedRowIndex, ID_COL_INDEX).toString());
            int currentQuantity = Integer.parseInt(orderTable.getModel().getValueAt(selectedRowIndex, QTY_COL_INDEX).toString());
            ShipItems currentItem = new ShipItems(id, currentQuantity);
            
            int maxQuantity = 0;

            for(Integer k: st.keys()){
                if(k == id){
                    maxQuantity = st.get(k).getQuantity();
                    choosenItem = st.get(k).toString();
                    break;
                }
            }                                      
            JLabel label4 = new JLabel(choosenItem);
              
            // Quantity List
            JComboBox qtyList = new JComboBox();

            for(int i = 1; i <= maxQuantity;i++){
                qtyList.addItem(i);
            }
            qtyList.setSelectedItem(currentQuantity);
            
            // Get Ship to column from Order Table
            String currentLocation = orderTable.getModel().getValueAt(selectedRowIndex, SHIP_COL_INDEX).toString();   
            
            // City List
            JComboBox cityList = new JComboBox(cities);
            cityList.setSelectedItem(currentLocation);

            // Add components to Panel
            panel.add(label1);
            panel.add(label2);
            panel.add(label3);
            panel.add(label4);
            panel.add(qtyList);
            panel.add(cityList);
            
            int result = JOptionPane.showConfirmDialog(null, panel, "Edit", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION)
            {
                // OK Option
                // Change the quantity and the city that choosen
                int editQuantity = Integer.parseInt(qtyList.getSelectedItem().toString());
                String editLocation = cityList.getSelectedItem().toString();
                
                for(String k: orderST.keys()){
                        if(currentLocation == k){
                            ArrayList<ShipItems> list = orderST.get(k);
                            list.remove(currentItem);
                            if(list.isEmpty()){
                                orderST.delete(k);
                            }
                            break;
                        }
                }
                
                ShipItems newItem = new ShipItems(id, editQuantity);
                if(orderST.contains(editLocation)){
                    ArrayList<ShipItems> list = orderST.get(editLocation);
                    list.add(newItem);
                    orderST.put(editLocation, list);
                }
                else{ // create new
                    ArrayList<ShipItems> list = new ArrayList<>();
                    list.add(newItem);
                    orderST.put(editLocation, list);
                }
             
                printOrderST();
                orderTable.getModel().setValueAt(editQuantity, selectedRowIndex, QTY_COL_INDEX);
                orderTable.getModel().setValueAt(editLocation, selectedRowIndex, SHIP_COL_INDEX);
              
            }
        }
    }//GEN-LAST:event_editOrderActionPerformed

    private void deleteOrderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteOrderActionPerformed
    {//GEN-HEADEREND:event_deleteOrderActionPerformed
       if(orderTable.getSelectedRow() != -1)
        {
            // remove selected row from the model
            if (JOptionPane.showConfirmDialog(null, "Are you sure to delete this order?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                {
                    // yes option
                    int[] selectedRows = orderTable.getSelectedRows();
                    for (int i = selectedRows.length - 1; i >= 0; i--)
                    {
                        int selectedRowIndex = selectedRows[i];
                        int id = Integer.parseInt(orderTable.getValueAt(selectedRowIndex, ID_COL_INDEX).toString());
                        int qty = Integer.parseInt(orderTable.getValueAt(selectedRowIndex, QTY_COL_INDEX).toString());                       
                        String location = orderTable.getValueAt(selectedRowIndex, SHIP_COL_INDEX).toString();
                      
                        if(orderST.contains(location)){
                            for(String k: orderST.keys())
                            {
                                if(location == k)
                                {
                                    ArrayList<ShipItems> list = orderST.get(k);
                                    ShipItems deleteItem = new ShipItems(id, qty);
                                    list.remove(deleteItem);
                                    if(list.isEmpty()){
                                        orderST.delete(location);
                                    }
                                    System.out.println("Deleting Item: " + deleteItem.toString());
                                    printOrderST();
                                    break;
                                }
                            }
                        }

                        orderModel.removeRow(selectedRowIndex);
                    }

                }
            }
    }//GEN-LAST:event_deleteOrderActionPerformed

    private void addOrderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addOrderActionPerformed
    {//GEN-HEADEREND:event_addOrderActionPerformed
        
        // Pop up a Panel
        JPanel panel = new JPanel(new GridLayout(0, 3));
        JLabel label1 = new JLabel("Choose Item");
        label1.setFont(new java.awt.Font("Tahoma", 1, 12));   
        JLabel label2 = new JLabel("Quantity");
        label2.setFont(new java.awt.Font("Tahoma", 1, 12));
        JLabel label3 = new JLabel("Ship To");
        label3.setFont(new java.awt.Font("Tahoma", 1, 12));
        
        // Items List
        JComboBox itemList = new JComboBox();
        for(Integer k: st.keys()){
            itemList.addItem(st.get(k));
        }
        
        itemList.setSelectedIndex(-1);

        
        // Quantity List
        JComboBox qtyList = new JComboBox();
       
        itemList.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                Items item = (Items)itemList.getSelectedItem();
                for(int i = 1; i <= item.getQuantity();i++){
                    qtyList.addItem(i);
                }
            }
        });
               
        // City List
        JComboBox cityList = new JComboBox(cities);
              
        panel.add(label1);
        panel.add(label2);
        panel.add(label3);
        panel.add(itemList);
        panel.add(qtyList);
        panel.add(cityList);
           
        int result = JOptionPane.showConfirmDialog(null, panel, "Add Order", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION)
        {
            // OK Option
            String[] newRow = new String[orderHead.length];
            Items itemSelected = (Items) itemList.getSelectedItem();           
            String[] newItem = itemSelected.getString().split(",");    
            int qty = Integer.parseInt(qtyList.getSelectedItem().toString());
            String location = cityList.getSelectedItem().toString();
            
            for (int i = 0; i < newItem.length; i++){
                //set the Quantity user input to newRow
                if(i == QTY_COL_INDEX){
                    newRow[i] = qty + "";
                }
                else{
                    newRow[i] = newItem[i];   
                }

            }

            
            newRow[SHIP_COL_INDEX] = location;
            
            // put into orderST
            if(orderST.contains(location)){
                ArrayList<ShipItems> list = orderST.get(location);
                ShipItems shipItem = new ShipItems(itemSelected.getId(), qty);
                list.add(shipItem);
                orderST.put(location, list);
                System.out.println(orderST.get(location).toString());
            }
            else{ // create new
                ArrayList<ShipItems> list = new ArrayList<>();
                ShipItems shipItem = new ShipItems(itemSelected.getId(), qty);
                list.add(shipItem);
                orderST.put(location, list);
                System.out.println(orderST.get(location).toString());
            }


            // Add new row to Order Table
            orderModel.addRow(newRow);
            
        }
    }//GEN-LAST:event_addOrderActionPerformed

   private String[][] createTable() {
       String[][] tableData = new String[st.size()][7];
       int i = 0;
   		for(Integer k: st.keys()) {
       		tableData[i][0] = "" + st.get(k).getId();
       		tableData[i][1] = "" + st.get(k).getName();
       		tableData[i][2] = "" + st.get(k).getCode();
       		tableData[i][3] = "" + st.get(k).getPrice();
       		tableData[i][4] = "" + st.get(k).getQuantity();
       		tableData[i][5] = "" + st.get(k).getDepartment();
       			
       		tableData[i][6] = st.get(k).getDateCreated();
       		
       		i++;
        }
                
        return tableData;
   }   
    
    
    private void printST(){
  	for(Integer k: st.keys()) {
            StdOut.println(st.get(k).toString());
       }
  	StdOut.println();
   }
    
    private void printOrderST(){
  	for(String k: orderST.keys()) {
            StdOut.println(k + ": " + orderST.get(k).toString());
       }
  	StdOut.println();
   }
    
    private String[] getCities(){
        ArrayList<String> list = new ArrayList<>();
        EdgeWeightedDigraph graph = sg.digraph();
        for(DirectedEdge e: graph.edges()){
            int v = e.from();
            int w = e.to();
            if(!list.contains(sg.nameOf(v))){
                list.add(sg.nameOf(v));
            }
            if(!list.contains(sg.nameOf(w))){
                list.add(sg.nameOf(w));
            }
        }
        cities = new String[list.size()];
              
        for(int i = 0; i < cities.length; i++){
            cities[i] = list.get(i);
        }
        
        return cities;
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new StockApp().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItem;
    private javax.swing.JButton addOrder;
    private javax.swing.JButton barChartBtn1;
    private javax.swing.JButton deleteItem;
    private javax.swing.JButton deleteOrder;
    private javax.swing.JButton editItem;
    private javax.swing.JButton editOrder;
    private javax.swing.JButton exportBtn1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JTable orderTable;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JButton pieChartBtn1;
    private javax.swing.JButton shipment;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
